# Site Settings
title: Community Carpool
email: ""
description: >
  A Safe, Convenient, Reliable and Economical rideshare solution for kids.
baseurl: "https://scottneaves.github.io/community-carpool/"
url: "http://localhost:4000"
twitter_username: taniarascia
github_username:  taniarascia
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
